### ISSUE TITLE
Unsupported lookup 'net_contains_or_equals' for CidrAddressField or join in the field not permitted

### ISSUE THREAD

**Issue by darkpixel** [jimfunk/django-postgresql-netfields#24]
I have a Network model defined as so:

```
from netfields import CidrAddressField, NetManager

class Network(BaseModel):
    block = CidrAddressField()
    description = models.CharField(max_length=255, null=True, blank=True) 
    objects = NetManager()
```

When I call:
```
Network.objects.filter(block__net_contains_or_equals='10.142.0.0/22')
```

Django 1.7 throws:
```
FieldError: Unsupported lookup 'net_contains_or_equals' for CidrAddressField or join on the field not permitted.
```

I am using the latest commit from git.

**Comment by shenek** [comment]
I managed to bypass this bug using following code:

    class PostgresNetContainsOrEquals(Lookup):
        lookup_name = 'net_contains_or_equals'

        def as_postgresql(self, qn, connection):
            lhs, lhs_params = self.process_lhs(qn, connection)
            rhs, rhs_params = self.process_rhs(qn, connection)

            return lhs + '>>=' + rhs, lhs_params + rhs_params
    CidrAddressField.register_lookup(PostgresNetContainsOrEquals)

**Comment by jimfunk** [comment]
This was fixed in 0.3. I forgot to close this at the time.

**Comment by bitcity** [comment]
Still get this error : 

`FieldError: Unsupported lookup 'net_contains_or_equals' for CidrAddressField or join on the field not permitted.`

Using 

`Django==1.8.12`
`django-netfields==0.5.3`

**Comment by jimfunk** [comment]
@bitcity Are you using NetManager? Do you have an example model/code this fails on?

**Comment by bitcity** [comment]
@jimfunk The problem was not adding `netfields` to installed apps (see https://github.com/jimfunk/django-postgresql-netfields/issues/26#issuecomment-102525294)

Now the lookup works but `select_related` fails with custom lookup. I'll dig a bit more and if needed, open a separate issue.
